### ISSUE TITLE
I'm not sure about the word "Recycle"

### ISSUE THREAD

**Issue by arnofaure** [RainbowCoder/Rainbow-Poem#36]
Dear mister @shiffman I'm not sure about the use of the word "Recycle!" at the line 14 in your amazing poem.

**Comment by arnofaure** [comment]
By the way is there a way to specify a specific line of code in the comment like this one?
Thanks for your help.

**Comment by shiffman** [comment]
Thanks for the pull request!  Yes, you can always add a comment at a line of code by clicking the "+" next to the line.  This has to be with a commit though, not just the code itself.  I'll add one now and @ mention you.
